[[main]]
none = "none"

[[main]]
name = "Blog"
pre = "blogger"
pageRef = "/posts"
identifier = "lffjdPgrHb"
weight = 4

[[main]]
name = "About"
pre = "fire"
pageRef = "about"
identifier = "h443Pkiequ"
weight = 3

[[footer]]
none = "none"
